TEMP: Don't build SetupWizard
Breaks build with Oreo source:
ERROR: /home/kreach3r/android/oreo/dev/packages/apps/KatsunaSetupWizard/src/com/katsuna/setupwizard/util/EnableAccessibilityController.java:61.63: continue_to_enable_accessibility cannot be resolved or is not a field
ERROR: /home/kreach3r/android/oreo/dev/packages/apps/KatsunaSetupWizard/src/com/katsuna/setupwizard/util/EnableAccessibilityController.java:65.63: enable_accessibility_canceled cannot be resolved or is not a field
ERROR: /home/kreach3r/android/oreo/dev/packages/apps/KatsunaSetupWizard/src/com/katsuna/setupwizard/util/EnableAccessibilityController.java:71.60: accessibility_enabled cannot be resolved or is not a field
ERROR: /home/kreach3r/android/oreo/dev/packages/apps/KatsunaSetupWizard/src/com/katsuna/setupwizard/util/EnableAccessibilityController.java:281.69: ACCESSIBILITY_SCRIPT_INJECTION cannot be resolved or is not a field
[ 74% 13622/18178] Building with Jack: out/target/common/obj/APPS/Dialer_intermediates/with-local/classes.dex
ninja: build stopped: subcommand failed.